# fly.toml app configuration file generated for greenup on 2025-06-29T17:49:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'greenup'
primary_region = 'fra'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'greenup.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

  [[http_service.checks]]
    method = 'GET'
    path = '/'
    protocol = 'http'
    timeout = '5s'
    interval = '30s'
    grace_period = '30s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
